version: '3.8'

services:
  app:
    build:
      context: .            # look in project root for Dockerfile
    container_name: log_app
    ports:
      - "3000:3000"         # host 3000 → container 3000

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config.yaml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - app

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3001:3000"         # host 3001 → container 3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus

# (optional) define a volume for Grafana persistence
volumes:
  grafana_data: {}
